image: python:3.8

variables:
  WORK_DIR: .
cache:
  key: '$CI_COMMIT_REF_SLUG'
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - deploy
  tags:
    - nyh1299
  script:
    - docker stop $(docker ps -aq) || true
    - docker system prune -af --volumes #필요 없는 이미지, 컨테이너 제거
    - docker build -t docker-test server
    - docker run -d -p 5000:5000 docker-test
