version: "3.7"

services:

  server:
    build: ./server
    container_name: server
    restart: always
    env_file:
      - dev.env
    expose:
      - 8080

  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:5000"
